{
    "openapi": "3.0.0",
    "info": {
        "title": "Changeorg Laravel API Rest Documentation",
        "description": "Changeorg Laravel API Rest Documentation",
        "contact": {
            "email": "ilarranaga@jesuitasformacion.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://laravel-changeorg-api.herokuapp.com/",
            "description": "API Server"
        }
    ],
    "paths": {
        "/api/login": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign in",
                "description": "Login by email, password",
                "operationId": "a3b306d14572d1f4bd6c064b3233e7b8",
                "requestBody": {
                    "description": "Pass user credentials",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "format": "email",
                                        "example": "user1@gmail.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password",
                                        "example": "PassWord12345"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Good credentials",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "access_token": {
                                            "type": "token",
                                            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xhcmF2ZWwtY2hhbmdlb3JnLWFwaS5oZXJva3VhcHAuY29tL2FwaS9sb2dpbiIsImlhdCI6MTY1MTU2NTE0MCwiZXhwIjoxNjUxNTY4NzQwLCJuYmYiOjE2NTE1NjUxNDAsImp0aSI6Ik1RdlBhdG1JTXZ3N29pbUkiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.GGsbe1V4CLxBCeKDuRb-t01T1-3Ak4DF_NIJqc3Ir8U"
                                        },
                                        "token_type": {
                                            "type": "string",
                                            "example": "bearer"
                                        },
                                        "expires_in": {
                                            "type": "integer",
                                            "example": "3600"
                                        },
                                        "user": {
                                            "type": "user",
                                            "example": {
                                                "user": {
                                                    "id": 1,
                                                    "name": "ilarra",
                                                    "email": "ilarra@gmail.com",
                                                    "email_verified_at": null,
                                                    "created_at": "2022-05-03T07:45:52.000000Z",
                                                    "updated_at": "2022-05-03T07:45:52.000000Z"
                                                }
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Wrong credentials response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "error": {
                                            "type": "string",
                                            "example": "Unauthorized. Either email or password is wrong."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign up",
                "description": "Regist by name, email, password",
                "operationId": "8a56853624e025573120a09a4c75d468",
                "requestBody": {
                    "description": "Pass new user credentials",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "name",
                                    "email",
                                    "password"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "user1"
                                    },
                                    "email": {
                                        "type": "string",
                                        "format": "email",
                                        "example": "user1@gmail.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "format": "password",
                                        "example": "PassWord12345"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Good credentials response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "User successfully registered"
                                        },
                                        "user": {
                                            "type": "user",
                                            "example": {
                                                "user": {
                                                    "id": 1,
                                                    "name": "ilarra",
                                                    "email": "ilarra@gmail.com",
                                                    "email_verified_at": null,
                                                    "created_at": "2022-05-03T07:45:52.000000Z",
                                                    "updated_at": "2022-05-03T07:45:52.000000Z"
                                                }
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Wrong credentials response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "error": {
                                            "type": "string",
                                            "example": "Unauthorized. Either email or password is wrong."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "description": "Logout",
                "operationId": "fe8f3429cd6979b3b4517e186505f9f9",
                "responses": {
                    "200": {
                        "description": "User correctly logged out",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "message": {
                                            "type": "string",
                                            "example": "User successfully signed out"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/me": {
            "get": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Me",
                "description": "Info of the logged in user",
                "operationId": "9d9bc556f927575aa492a88c28fe5908",
                "responses": {
                    "200": {
                        "description": "User information",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "user": {
                                            "type": "user",
                                            "example": {
                                                "user": {
                                                    "id": 1,
                                                    "name": "ilarra",
                                                    "email": "ilarra@gmail.com",
                                                    "email_verified_at": null,
                                                    "created_at": "2022-05-03T07:45:52.000000Z",
                                                    "updated_at": "2022-05-03T07:45:52.000000Z"
                                                }
                                            }
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/refresh": {
            "post": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign in",
                "description": "Login by email, password",
                "operationId": "2c27d311a2876560fcb5a754b556cdc5",
                "responses": {
                    "200": {
                        "description": "Good credentials",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "access_token": {
                                            "type": "token",
                                            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xhcmF2ZWwtY2hhbmdlb3JnLWFwaS5oZXJva3VhcHAuY29tL2FwaS9sb2dpbiIsImlhdCI6MTY1MTU2NTE0MCwiZXhwIjoxNjUxNTY4NzQwLCJuYmYiOjE2NTE1NjUxNDAsImp0aSI6Ik1RdlBhdG1JTXZ3N29pbUkiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.GGsbe1V4CLxBCeKDuRb-t01T1-3Ak4DF_NIJqc3Ir8U"
                                        },
                                        "token_type": {
                                            "type": "string",
                                            "example": "bearer"
                                        },
                                        "expires_in": {
                                            "type": "integer",
                                            "example": "3600"
                                        },
                                        "user": {
                                            "type": "user",
                                            "example": [
                                                {
                                                    "id": 1,
                                                    "name": "ilarra",
                                                    "email": "ilarra@gmail.com",
                                                    "email_verified_at": null,
                                                    "created_at": "2022-05-03T07:45:52.000000Z",
                                                    "updated_at": "2022-05-03T07:45:52.000000Z"
                                                }
                                            ]
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Wrong credentials response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "error": {
                                            "type": "string",
                                            "example": "Unauthorized. Either email or password is wrong."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearer_token": []
                    }
                ]
            }
        },
        "/api/peticiones": {
            "get": {
                "tags": [
                    "Peticiones"
                ],
                "summary": "Devuelve las peticiones",
                "operationId": "b91666912c965c676b40d2d7d767954b",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "peticiones": {
                                            "type": "array",
                                            "items": {
                                                "properties": {
                                                    "id": {
                                                        "type": "number",
                                                        "example": ""
                                                    },
                                                    "titulo": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "descripcion": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "destinatario": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "firmantes": {
                                                        "type": "number",
                                                        "example": ""
                                                    },
                                                    "estado": {
                                                        "type": "string",
                                                        "example": ""
                                                    },
                                                    "user_id": {
                                                        "type": "number",
                                                        "example": ""
                                                    },
                                                    "categoria_id": {
                                                        "type": "number",
                                                        "example": ""
                                                    }
                                                },
                                                "type": "object"
                                            },
                                            "example": [
                                                {
                                                    "id": 1,
                                                    "titulo": "lalala3",
                                                    "descripcion": "lalala3",
                                                    "destinatario": "lalala3",
                                                    "firmantes": 0,
                                                    "estado": "pendiente",
                                                    "user_id": 1,
                                                    "categoria_id": 1,
                                                    "image": null,
                                                    "created_at": "2022-05-03T07:47:11.000000Z",
                                                    "updated_at": "2022-05-03T07:50:31.000000Z"
                                                },
                                                {
                                                    "id": 11,
                                                    "titulo": "lalala2",
                                                    "descripcion": "lalala2",
                                                    "destinatario": "lalala2",
                                                    "firmantes": 0,
                                                    "estado": "pendiente",
                                                    "user_id": 1,
                                                    "categoria_id": 1,
                                                    "image": null,
                                                    "created_at": "2022-05-03T07:47:22.000000Z",
                                                    "updated_at": "2022-05-03T07:47:22.000000Z"
                                                },
                                                {
                                                    "id": 21,
                                                    "titulo": "lalala3",
                                                    "descripcion": "lalala3",
                                                    "destinatario": "lalala3",
                                                    "firmantes": 0,
                                                    "estado": "pendiente",
                                                    "user_id": 1,
                                                    "categoria_id": 1,
                                                    "image": null,
                                                    "created_at": "2022-05-03T08:06:02.000000Z",
                                                    "updated_at": "2022-05-03T08:06:02.000000Z"
                                                }
                                            ]
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/mispeticiones/": {
            "get": {
                "tags": [
                    "Peticiones"
                ],
                "summary": "Get list of peticiones of the logged in user",
                "description": "Returns list of peticiones of the logged in user",
                "operationId": "3871972bac61a1afd66ad9ca7b638fad",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#Peticiones"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthenticated"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/api/peticiones/{id}": {
            "get": {
                "tags": [
                    "Peticiones"
                ],
                "summary": "Muestra el detalle de una petición",
                "operationId": "2c711e8f3241fad7fb3766afc631b04e",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Peticione id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mostrar la petición."
                    },
                    "default": {
                        "description": "Ha ocurrido un error."
                    }
                }
            },
            "put": {
                "tags": [
                    "Peticiones"
                ],
                "summary": "Update existing peticione",
                "description": "Returns updated peticione data",
                "operationId": "f65dfdf1140faa8f9eaf32275765e293",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Peticione id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#Peticione"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#Peticione"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthenticated"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Resource Not Found"
                    }
                }
            }
        },
        "/api/users/firmas": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Mostrar peticiones firmadas por el usuario logueado",
                "operationId": "80dbcadf913999ea1ada57c555d17f36",
                "responses": {
                    "200": {
                        "description": "Mostrar todas las peticiones."
                    },
                    "default": {
                        "description": "Ha ocurrido un error."
                    }
                }
            }
        }
    },
    "components": {
        "responses": {
            "400": {
                "description": "Invalid request",
                "content": {
                    "application/json": {
                        "schema": {}
                    }
                }
            }
        }
    }
}